version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14
        USER_UID: 1000
        USER_GID: 1000
        THEME: https://github.com/denysdovhan/spaceship-prompt
    volumes:
      - ..:/app:delegated
    command: sleep infinity
    user: node
    networks:
      - b2b-network
networks:
  b2b-network:
    external: true